#!/bin/sh
# udhcpc script edited by Tim Riker <Tim@Rikers.org>

RESOLV_CONF_APPEND="/tmp/dnsAppend.conf"
RESOLV_CONF="/tmp/resolv.conf"

[ -n "$1" ] || { echo "Error: should be called from udhcpc"; exit 1; }

NETMASK=""
[ -n "$subnet" ] && NETMASK="netmask $subnet"
BROADCAST="broadcast +"
[ -n "$broadcast" ] && BROADCAST="broadcast $broadcast"

case "$1" in
#	deconfig)
#		;;

	renew|bound)
		echo "Recreating $RESOLV_CONF"
		echo -n > $RESOLV_CONF-$$
		[ -n "$domain" ] && echo "search $domain" >> $RESOLV_CONF-$$
		for i in $dns ; do
			echo " Adding DNS server $i"
			echo "nameserver $i" >> $RESOLV_CONF-$$
		done
		if [ -f "$RESOLV_CONF_APPEND" ];then
		  cat $RESOLV_CONF_APPEND >> $RESOLV_CONF-$$
		fi
		mv $RESOLV_CONF-$$ $RESOLV_CONF
		;;
esac

exit 0
