/* this file should be generated by mkpart.py,please do not modify this file manually*/

#ifndef CVIPART_H
#define CVIPART_H
#define CONFIG_ENV_IS_IN_NAND
#define MTDPARTS_DEFAULT    "mtdparts=cvsnfc:2560K(boot),256K(env),4M(kernel.A),3M(rootfs.A),20M(firmware.A),4M(kernel.B),3M(rootfs.B),20M(firmware.B),8M(config.A),8M(config.B),512K(update),-(data)"
#define CONFIG_ENV_OFFSET 0x280000
#define CONFIG_ENV_SIZE 0x20000
#define CONFIG_ENV_OFFSET_REDUND 0x2A0000
#define CONFIG_ENV_SIZE_REDUND 0x20000

#define PARTS_ENV \
"partition={\
\"flashImgSize\":\"74M\",\
\"partitionTable\":[\
{\"name\":\"boot\",\"file\":\"boot.bin\",\"size\":\"2560K\"},\
{\"name\":\"env\",\"size\":\"256K\"},\
{\"name\":\"kernel.A\",\"file\":\"kernel.bin\",\"size\":\"4M\"},\
{\"name\":\"rootfs.A\",\"file\":\"rootfs.bin\",\"size\":\"3M\"},\
{\"name\":\"firmware.A\",\"file\":\"firmware.bin\",\"size\":\"20M\"},\
{\"name\":\"kernel.B\",\"file\":\"kernel.bin\",\"size\":\"4M\"},\
{\"name\":\"rootfs.B\",\"file\":\"rootfs.bin\",\"size\":\"3M\"},\
{\"name\":\"firmware.B\",\"file\":\"firmware.bin\",\"size\":\"20M\"},\
{\"name\":\"config.A\",\"size\":\"8M\"},\
{\"name\":\"config.B\",\"size\":\"8M\"},\
{\"name\":\"update\",\"size\":\"512K\"}\
]\
}\0" \
"systemSelect=A\0" \
"fip_PART_OFFSET=0x0\0" \
"fip_PART_SIZE=0x280000\0" \
"ENV_PART_OFFSET=0x280000\0"\
"ENV_PART_SIZE=0x40000\0"\
"BOOT_PART_OFFSET=0x2C0000\0" \
"BOOT_PART_SIZE=0x400000\0" \
"ROOTFS_PART_OFFSET=0x6C0000\0" \
"ROOTFS_PART_SIZE=0x300000\0" \
"APP_PART_OFFSET=0x9C0000\0" \
"APP_PART_SIZE=0x1400000\0" \
"BOOT2_PART_OFFSET=0x1DC0000\0" \
"BOOT2_PART_SIZE=0x400000\0" \
"ROOTFS2_PART_OFFSET=0x21C0000\0" \
"ROOTFS2_PART_SIZE=0x300000\0" \
"APP2_PART_OFFSET=0x24C0000\0" \
"APP2_PART_SIZE=0x1400000\0" \
"CONFIGS_PART_OFFSET=0x38C0000\0" \
"CONFIGS_PART_SIZE=0x800000\0" \
"CONFIGS2_PART_OFFSET=0x40C0000\0" \
"CONFIGS2_PART_SIZE=0x800000\0" \
"UPDATE_PART_OFFSET=0x48C0000\0" \
"UPDATE_PART_SIZE=0x80000\0" \
"DATA_PART_OFFSET=0x4940000\0"	\
"DATA_PART_SIZE=0x8000000000000000\0"
#endif