#!/bin/sh
insmod cv182x_base.ko
insmod cv182x_vip.ko
insmod cvi_mipi_rx.ko
insmod cv182x_sensor_i2c.ko
insmod cv182x_saradc.ko
#insmod cv182x_wdt.ko
insmod cv182x_clock_cooling.ko

insmod cv182x_tpu.ko
insmod cv182x_jpeg.ko
insmod cv182x_vcodec.ko
insmod cv182x_pwm.ko

exit $?
